name: Run bot V1 (unused and superseded by V2)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2.3.4
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run the bot
        run: |-
          pip install -r V1/requirements.txt
          python V1/runebot.py